import Link from 'next/link';
import { remote, communityOrigin } from '@/server/kitchen/community';
import { parseSnapshot, type Publication } from '@/lib/community-contract';
export const dynamic='force-dynamic';
export default async function Explore({searchParams}:{searchParams:Promise<{q?:string}>}) {
 const {q}=await searchParams;let recipes:Publication[]=[];let available=!!communityOrigin();
 if(available)try{recipes=(await remote<{recipes:Publication[]}>(`recipes?search=${encodeURIComponent(q||'')}`)).recipes;recipes.forEach(r=>parseSnapshot(r.snapshot));}catch{available=false;}
 return <main className="mx-auto max-w-4xl space-y-6 p-6"><Link className="underline" href="/">Sous Chef</Link><h1 className="text-3xl font-semibold">Recipes from the community</h1><p>Download a recipe, then use Import in your local recipe library. No kitchen account is required to browse.</p><form className="flex gap-3"><input aria-label="Search recipes" name="q" defaultValue={q} className="min-w-0 flex-1 rounded border p-3"/><button className="rounded bg-emerald-700 px-4 text-white">Search</button></form>{!available?<p role="status">The community service is not connected or is temporarily unavailable.</p>:recipes.length===0?<p>No recipes found. Be the first to share one from your kitchen.</p>:<div className="grid gap-4 sm:grid-cols-2">{recipes.map(r=><article key={r.id} className="space-y-3 rounded-xl border p-5"><h2 className="text-xl font-semibold">{r.snapshot.title}</h2><p>By {r.author.name}</p><p>{r.snapshot.description}</p><details><summary>View recipe</summary><ul className="my-3 list-disc pl-5">{r.snapshot.ingredients.map((i,n)=><li key={n}>{i.quantity} {i.unit} {i.name}</li>)}</ul><ol className="list-decimal pl-5">{r.snapshot.steps.map((s,n)=><li key={n}>{s.text}</li>)}</ol></details><a className="inline-block underline" href={`/api/community/recipes/${encodeURIComponent(r.id)}`}>Download recipe</a></article>)}</div>}<Link className="inline-block underline" href="/inventory">Open your kitchen to publish a recipe</Link></main>;
}
