-- AlterTable
ALTER TABLE "Recipe"
ADD COLUMN "caloriesKcal" DOUBLE PRECISION,
ADD COLUMN "proteinGrams" DOUBLE PRECISION,
ADD COLUMN "carbsGrams" DOUBLE PRECISION,
ADD COLUMN "fatGrams" DOUBLE PRECISION;
